modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "${modrinth}"
authors = "werdei, LegendarySpy, Etos2"
description = "${description}"
logoFile = "logo.png"

[["dependencies.${id}"]]
modId = "neoforge"
type = "required"

[["dependencies.${id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"

[[mixins]]
config = "${id}.mixins.json"
